### PR TITLE
Fix crash, close italic tag

### PR DESCRIPTION
**Pull request by bvtsang**
Crash details: https://gfycat.com/UnrulyHugeHarborporpoise

### CODE REVIEW

**Comment by darth62969** [comment]
Trying use Lucidia Sans for that the LSans.tff thing, That is only Temporary cause i really want to use standard system Fonts, can't figure out how though.

**Comment by bvtsang** [comment]
If you want to force everyone to use a font, you'll have to include it in the game and reference it. There's no other guarantee that everyone will have Lucida Sans installed.

**Comment by darth62969** [comment]
standard sans... is there a way to make an alternative? 

also my spelling sucks, Lucida Sans.

**Comment by bvtsang** [comment]
RenPy's default font is DejaVu Sans. If you'd like, you can have everyone use that instead so that you won't need to include new fonts.

**Comment by darth62969** [comment]
nah but lucida sans should be on everyone's computer, it's been around on windows machines since xp, but i want identical type to what i am using on the buttons, inkscape says it is "sans" but i don't know where this "sans" is coming from, so i don't know what sans-serif typeface it is... then i also don't like how ren'py does fonts anyway... but whatever.

**Comment by bvtsang** [comment]
Lucida fonts are [not included by default on Linux machines](https://askubuntu.com/questions/98579/how-do-i-get-lucida-fonts) (or at least on those with Ubuntu). [Lucida Sans Unicode isn't included on Mac OS X, but Lucida Grande is](https://en.wikipedia.org/wiki/Lucida_Sans_Unicode) (but then was replaced by Helvetica Neue for Yosemite).

When you specify a font as a simple font family like sans-serif, it's up to the operating system or program to determine what that font is.
- For Mac OS X, [it's Helvetica](https://webmasters.stackexchange.com/questions/33793/what-is-the-default-serif-sans-serif-and-monospace-font-family-for-mac-os-x).
- For Windows I'm not sure, but depending on your version it's probably either [Arial, Segoe UI](https://www.neowin.net/forum/topic/1249402-is-arial-the-default-sans-serif-font-in-windows-10/), or [Calibri](http://windowssecrets.com/forums/showthread.php/119896-Default-fonts-in-Windows-7).
- For Linux, you would need to [look under `/etc/fonts/`](http://ubuntuforums.org/showthread.php?t=1675235) or [use some sort of utility](http://stackoverflow.com/a/2539979) or something. Determining this will probably vary by distribution.

Overall, if you're not okay with RenPy's default DejaVu Sans, you should specify and include the font you want to use.

**Pull request merged**
